//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Resources
{
    using System.Reflection;
    using System;

    /// <summary>
    ///    ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラス。
    /// </summary>
    // このクラスは、StronglyTypedResourceBuilder 
    // クラスにより、ResGen または Visual Studio のようなツールで自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集し、ResGen を
    // /str オプションで再実行するか、VS プロジェクトを再ビルドします。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exception
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Exception()
        {}

        /// <summary>
        ///    このクラスに使用される、キャッシュされた ResourceManager のインスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Resources.Exception", typeof(Exception).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///    現在のスレッドの CurrentUICulture プロパティを、
        ///    厳密に型指定されたリソース クラスを使用して、すべてのリソース ルックアップに対して上書きします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///    対象機能の利用が認められていません に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string AccessDenied
        {
            get
            {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///    既に処理済の情報です に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string ActionUnprocessing
        {
            get
            {
                return ResourceManager.GetString("ActionUnprocessing", resourceCulture);
            }
        }

        /// <summary>
        ///    ログイン状態が有効ではありません に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication
        {
            get
            {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }

        /// <summary>
        ///    既に受渡日を迎えています に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string CashflowBeforeEqualsDay
        {
            get
            {
                return ResourceManager.GetString("CashflowBeforeEqualsDay", resourceCulture);
            }
        }

        /// <summary>
        ///    受渡日を迎えていないため実現できません に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string CashflowRealizeDay
        {
            get
            {
                return ResourceManager.GetString("CashflowRealizeDay", resourceCulture);
            }
        }

        /// <summary>
        ///    未到来の受渡日です に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string CashInOutAfterEqualsDay
        {
            get
            {
                return ResourceManager.GetString("CashInOutAfterEqualsDay", resourceCulture);
            }
        }

        /// <summary>
        ///    既に発生日を迎えています に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string CashInOutBeforeEqualsDay
        {
            get
            {
                return ResourceManager.GetString("CashInOutBeforeEqualsDay", resourceCulture);
            }
        }

        /// <summary>
        ///    出金可能額を超えています に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string CashInOutWithdrawAmount
        {
            get
            {
                return ResourceManager.GetString("CashInOutWithdrawAmount", resourceCulture);
            }
        }

        /// <summary>
        ///    マイナスを含めない数字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string DomainAbsAmount
        {
            get
            {
                return ResourceManager.GetString("DomainAbsAmount", resourceCulture);
            }
        }

        /// <summary>
        ///    マイナスを含めない数字を入力してください。 に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string DomainAbsAmountZero
        {
            get
            {
                return ResourceManager.GetString("DomainAbsAmountZero", resourceCulture);
            }
        }

        /// <summary>
        ///    既に登録されているIDです に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicateId
        {
            get
            {
                return ResourceManager.GetString("DuplicateId", resourceCulture);
            }
        }

        /// <summary>
        ///    情報が見つかりませんでした に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string EntityNotFound
        {
            get
            {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///    サーバー側で問題が発生した可能性があります に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string Internal
        {
            get
            {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }

        /// <summary>
        ///    ログインに失敗しました に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///    入力してください に類似したローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertyValueRequired
        {
            get
            {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
    }
}